

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./backend/db/aplikasi.db:/app/db/aplikasi.db
    ports:
      - "3000:3000"   
    environment:
      - NAME=Ignatius

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "80:80"
    environment:
      - NAME=Ignatius

