version: '3.8'

services:
  aplikasi-pertamaku-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  aplikasi-pertamaku-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - aplikasi-pertamaku-backend
  aplikasi-pertamaku-nginx:
    image: nginx:latest
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/certs:/etc/ssl/certs
    ports:
      - "443:443"
    depends_on:
      - aplikasi-pertamaku-backend
      - aplikasi-pertamaku-frontend
